# Site settings
title: He Run
twitter_username: herun1988
name: He Run

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: http://automateddeveloper.blogspot.com/
# - title: GitHub
#   url: https://github.com/robhinds
# - title: StackOverflow
#   url: http://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://sg.linkedin.com/in/run-he-61677b2b

#Any buzzword skills you want to include
skills:
 - Java
 - Objective C (iOS)
 - JPA
 - SQL
 - REST
 - Solution Architecture
 - AngularJS
 - VB, VBA
 - Web Development (HTML, PHP, CSS, JavaScript)
 - Design Patterns
 - Agile Scrum
 - API Gateway
 - JBoss Fuse (ESB)
 - Nevis
 - Axway Synchrony
 - Splunk
 - Activiti

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Architect
   start: Jul 2016
   end: Ongoing
   employer: NCS Pte Ltd
   description: Design and propose IT solutions based on customer's needs and limitations. Focus on API Gateway, ESB, Microservices and NOSQL.
 - title: Software Engineer
   start: Dec 2014
   end: Jul 2016
   employer: AdNovum, Singapore
   description: Main iOS developer of TWINT payment App and merchant app. Communicate and coordinate in virtual teams across different countries, such as Europe and Vietnam. Develop Workflow product using AngujarJS and Activiti.
 - title: Application Consultant
   start: Jul 2012
   end: Dec 2014
   employer: NCS Pte Ltd
   description: Develop, enhance, customize and test Banking solutions. Provide professional, accurate and satisfactory consultancy to customers.

#Education is required
education:
 - level: Master of Computing
   date: 2015
   subject: Information System
   school: National University of Singapore
 - level: Bachelor of Engineering
   date: 2012
   subject: Computer Engineering
   school: Nanyang Technological University, Singapore

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/9c22c909f0961c97cf5592364b567104
   courses:
      

    - title: Business Writing
      link: https://www.coursera.org/learn/writing-for-business
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/ec/c9bc70267211e6ba0837975d75ec8e/specialization-logo.jpg?auto=format&dpr=1&w=200&h=112&fit=crop
      date: 2016       
    - title: Graphic Design
      link: https://www.coursera.org/learn/presentation-design
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/ec/c9bc70267211e6ba0837975d75ec8e/specialization-logo.jpg?auto=format&dpr=1&w=200&h=112&fit=crop
      date: 2016    
    - title: Learning How to Learn
      link: https://www.coursera.org/learn/learning-how-to-learn
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/6e/c02c90d08611e3bb7b4ba94dd73d39/Learning-How-to-Learn-Logo-with-text.png?auto=format&dpr=1&w=200&h=112&fit=crop
      date: 2015   
    - title: Moralities of Everyday Life
      link: https://www.coursera.org/learn/moralities
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/34/66add02e4e11e6a8cbd1b554b71fa2/shutterstock_45601228-sized.jpg?auto=format&dpr=1&w=100&h=100&fit=fill&bg=FFF
      date: 2014     
    - title: Essentials of Entrepreneurship - Thinking & Action
      link: https://www.coursera.org/learn/entrepreneurial-thinking
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/af/09c36049ad11e49965db576a13e532/Entrepreneurship-Course.jpg?auto=format&dpr=1&w=100&h=100&fit=fill&bg=FFF
      date: 2014
    - title: The Art of Negotiation
      link: https://www.coursera.org/learn/art-of-negotiation
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/64/70158066ad11e498d6d9c80ec88b73/Negotiation-r2a.jpg?auto=format&dpr=1&w=100&h=100&fit=fill&bg=FFF
      date: 2014
    - title: Introduction to Philosophy
      link: https://www.coursera.org/learn/philosophy
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/introphil/large-icon.png?auto=format&dpr=1&w=100&h=100&fit=fill&bg=FFF
      date: Jan 14, 2014
    - title: What a Plant Knows
      link: https://www.coursera.org/learn/plantknows
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/91/8ec3b0878911e58fe52b33c777c38b/what-a-plant-knows.jpg?auto=format&dpr=1&w=100&h=100&fit=fill&bg=FFF
      date: Dec 3, 2013

#List of interesting Github repo/projects to include - optional
# github:


#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

#Mobile apps section is optional
apps:
 - name: Colofusion
   platform: iOS
   url: https://itunes.apple.com/us/app/colofusion-free-colored-tiles/id1101862896?ls=1&mt=8
   description: A simple game to see how well a person can distinguish subtle differences in colors
 - name: Colofusion
   platform: Android
   url: https://play.google.com/store/apps/details?id=com.mintistudio.game.ColorChallenge
   description: A simple game to see how well a person can distinguish subtle differences in colors   

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
#   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
#   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
